"""Focused tests for the PSB reader."""

from datetime import datetime
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import pytest

from turn_by_turn import psb, read_tbt
from turn_by_turn.structures import TbtData

INPUTS_DIR = Path(__file__).parent / "inputs"
PSB_FILE = INPUTS_DIR / "test_psb.sdds"
LHC_CONVERTED_FILE = INPUTS_DIR / "test_psb_as_lhc.sdds"


@pytest.fixture(scope="module")
def _psb_file() -> Path:
    return Path(PSB_FILE).resolve()


@pytest.fixture(scope="module")
def _lhc_converted_file() -> Path:
    """This file was generated by a script that can be found in the psbop/Multiturn
    folder, it is a non generic converter that takes the original PSB file and
    produces an LHC-like SDDS file with the same data, was used to make compatible
    with the analysis gui. Ask Ewen for details if needed."""
    return Path(LHC_CONVERTED_FILE).resolve()


def test_read_psb_core_fields(_psb_file):
    """Smoke test for the PSB reader and key parsed fields."""
    tbt_data = psb.read_tbt(_psb_file)

    assert isinstance(tbt_data, TbtData)
    assert tbt_data.nbunches == 1
    assert tbt_data.nturns == 10000
    assert len(tbt_data.matrices) == 1

    matrix = tbt_data.matrices[0]
    assert matrix.X.shape == (16, 10000)
    assert matrix.Y.shape == (16, 10000)
    assert not matrix.X.isna().any().any()
    assert not matrix.Y.isna().any().any()

    bpm_names = list(matrix.X.index)
    assert bpm_names[0] == "BR3.BPM1L3"
    assert bpm_names[-1] == "BR3.BPM16L3"

    assert tbt_data.meta["source_datatype"] == "psb"
    assert tbt_data.meta["file"] == _psb_file
    assert isinstance(tbt_data.meta["date"], datetime)


def test_read_psb_via_io_dispatch(_psb_file):
    """Ensure top-level IO dispatch resolves to the PSB reader."""
    tbt_data = read_tbt(_psb_file, datatype="psb")
    assert isinstance(tbt_data, TbtData)
    assert tbt_data.nbunches == 1
    assert tbt_data.nturns == 10000


def test_psb_and_lhc_converted_data_match(_psb_file, _lhc_converted_file):
    """Core regression test: PSB data must match the converted LHC file values."""
    tbt_psb = read_tbt(_psb_file, datatype="psb")
    tbt_lhc = read_tbt(_lhc_converted_file, datatype="lhc")

    assert tbt_psb.nbunches == tbt_lhc.nbunches
    assert tbt_psb.nturns == tbt_lhc.nturns

    matrix_psb = tbt_psb.matrices[0]
    matrix_lhc = tbt_lhc.matrices[0]

    assert list(matrix_psb.X.index) == list(matrix_lhc.X.index)
    assert list(matrix_psb.Y.index) == list(matrix_lhc.Y.index)

    np.testing.assert_allclose(matrix_psb.X.to_numpy(), matrix_lhc.X.to_numpy(), rtol=0.0, atol=1e-8)
    np.testing.assert_allclose(matrix_psb.Y.to_numpy(), matrix_lhc.Y.to_numpy(), rtol=0.0, atol=1e-8)


def test_hor_bunch_id_fallback_and_truncation(monkeypatch, tmp_path):
    """Cover fallback to horBunchId and truncation when IDs array is longer than nbunches."""
    fake_values = {
        psb.N_BUNCHES: 1,
        psb.N_TURNS: 2,
        psb.ACQ_STAMP: 1775638241670,
        psb.BPM_NAMES: np.array(["BPM.TEST"], dtype=object),
        psb.HOR_BUNCH_ID: np.array([7, 8], dtype=int),
        psb.POSITIONS["X"]: np.array([1.0, 2.0], dtype=float),
        psb.POSITIONS["Y"]: np.array([3.0, 4.0], dtype=float),
    }
    fake_sdds_file = SimpleNamespace(values=fake_values)
    monkeypatch.setattr(psb.sdds, "read", lambda _path: fake_sdds_file)

    dummy_file = tmp_path / "dummy.sdds"
    tbt_data = psb.read_tbt(dummy_file)

    assert tbt_data.nbunches == 1
    assert tbt_data.bunch_ids is not None
    assert len(tbt_data.bunch_ids) == 1
    assert tbt_data.bunch_ids[0] == 7
    assert tbt_data.matrices[0].X.shape == (1, 2)
    assert tbt_data.matrices[0].Y.shape == (1, 2)
